enable_sidebar:
  default: true
  description: Enable tags sidebar
enable_calendar_widget:
  default: true
  description: Enable Calendar Widget
number_of_tags:
  default: 50
  min: 3
  max: 200
  description: Number of tags to display in sidebar
sort_by_popularity:
 default: false
 type: bool
 description: When checked tags are sorted by popularity
